name: ExoticTrades-Bluemap
version: '${version}'
main: io.github.leralix.extrade.squaremap.ExoticTradesBluemap
api-version: '1.19'
depend:  [ExoticTrades, dynmap, SphereLib]
commands:
  trademap:
    description: ExoticTrades admin command
    permission: extrade_dynmap.admin
    usage: /<command>