name: extrade-squaremap
version: '${version}'
main: io.github.leralix.extrade.squaremap.ExoticTradesSquaremap
api-version: '1.19'
depend:  [ExoticTrades, squaremap, SphereLib]
commands:
  trademap:
    description: ExoticTrades admin command
    permission: extrade_dynmap.admin
    usage: /<command>